version: '3.7'

networks:
  backend:
    driver: bridge

services:
  workspace:
    tty: true
    build:
      context: ./workspace
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www/html
    networks:
      - backend
